steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t us-west2-docker.pkg.dev/store-microservices-418519/image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_MS_DATABASE_URL=$$DATABASE_URL .
  secretEnv: ['DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-west2-docker.pkg.dev/store-microservices-418519/image-registry/orders-ms',
    ]

availableSecrets:
  secretManager:
  - versionName: projects/703693373505/secrets/ORDERS_MS_DATABASE_URL/versions/1
    env: 'DATABASE_URL'